# ==========================================
# PUERTO DEL SERVIDOR
# ==========================================
server.port=9090

# ==========================================
# CONFIGURACION DE SEGURIDAD (Azure AD B2C)
# ==========================================
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://duocsemana5.b2clogin.com/296c652a-f639-4c16-b377-09fed74c2667/v2.0/
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://duocsemana5.b2clogin.com/duocsemana5.onmicrosoft.com/discovery/v2.0/keys?p=b2c_1_guiasdespacho_login

# ==========================================
# CONFIGURACION DE ALMACENAMIENTO (AWS S3)
# ==========================================
aws.s3.bucket-name=guias-despacho-duoc-2026
aws.s3.access-key=ASIAYZKOXWE6UZEG3KF5
aws.s3.secret-key=C5GRdeHKPc8IAnGTXfnvkwfaXjAlVNblAmI/Q7v2
aws.s3.session-token=IQoJb3JpZ2luX2VjENf//////////wEaCXVzLXdlc3QtMiJGMEQCIHw5a3iIopLuSXZUWEPQETYmGsja28m4Mwr861CRsRShAiAwDwAwOJUCe4oO16sK5vLGRkp0PJca+DwSGVcbvePHySq1Agig//////////8BEAEaDDYwNDE0NDkwNjU1NyIME97ZsdSvVcvTI38HKokCY+FqPRuUox9swWzANyxXkr7C8a63ft+ohrP8pXJeM4K8NKTGcmpZFyPJlvtJpX0ePSgo7kaKGourK1BOLC2LUUJqyXwTB6aPXMpy86z0LC/vMCVCH39bRlEADNVSNEj3gL97Mim5SRm473B9dgGettUVsbcNJZDTLCiIjL0la5vN2K9lC5qjcNspY/7UxZGBpeuJkAI5p4750zP+s3NPflRMYsysKcRwpPqm5potkaRXe75ga7ObIUOSzgOvYvI+zZzarjjGKL/WvtgnOhnJwKCf+U6hRK8Dlngf+5Dg0MD5WzRk+V1MCowYxkAVk1imC5YsppetVSFx08hSqSJv941hu+/01dZ40TDIwYbSBjqeAd87EnlHz/2V8asoSSzXWRFcKVJisq/RzLRv/5ucjYnG7cWdxAwI+WsytpbV4HnkrkFR/IC0LReO2D/Sz4llCH4OoX8EdVbHPaKBX4x/cxCUeHZ4czXqWnC+nL0iR1r3I1boGs6BKUMDHSd7GMd80DnQxU+iKiLn+s1ToagLOda2MQVnUfgf6vF6ph1aYyA7kEhuKCNDdGU5eTRETdHX
aws.s3.region=us-east-1

# ==========================================
# DESACTIVAR BASE DE DATOS
# ==========================================
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration