# ==========================================
# PUERTO DEL SERVIDOR
# ==========================================
server.port=9090

# ==========================================
# CONFIGURACION DE SEGURIDAD Y S3
# ==========================================
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://duocsemana5.b2clogin.com/296c652a-f639-4c16-b377-09fed74c2667/v2.0/
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://duocsemana5.b2clogin.com/duocsemana5.onmicrosoft.com/discovery/v2.0/keys?p=b2c_1_guiasdespacho_login

aws.s3.bucket-name=guias-despacho-duoc-2026
aws.s3.access-key=ASIAYZKOXWE6ZQGOKRKN
aws.s3.secret-key=Hw21fsDvN2hBqFRnG7EczrINqr9rD8pwnRGe6cHv
aws.s3.session-token=IQoJb3JpZ2luX2VjENv//////////wEaCXVzLXdlc3QtMiJIMEYCIQCiBrW0JtxA1UNCIwvSIcJOXIc4O/1BgQ02jKuMmSfB3QIhALnJRb9PBcnGEWMx2icD5WHkEGIj8fLa5w4e2g64v+/rKrUCCKT//////////wEQARoMNjA0MTQ0OTA2NTU3Igz3VNfD3Wf2tq5h/ogqiQLNkEV3k0bi/4HW6b5mz/QsZRaZnPrdbZ0tY3QUYKpvZ9EHnVaKfESF8X3jBLUvPfY5orcKqvZYGAW/G2wJhABPoBaAOanGNAITa6O59CDN9ySETECvM3z1kINczhjJaSI46pg6GvqhM+0U8tmrYzPHKKo5pi5lAXOSUmxMASpBEpjyO/ZkZgB+Vb+BZbdgewXgRrqN4Z19Q5cfvzwvyolMwkkRBvrVdHlXTnDqR2mu4Y9oKQi9mXdKQNcV6PhJWLAj64t+JNPdUicTy4bE0r92/791PN+F8NNbmMGXvKAb+OZ4JTcyIK4TQJW8rfcr2vOmQKj+XZvRboTFwpL/CSaoepz4o8jRcT3eMLC1h9IGOpwBbj//7UrtghSc7fSnoHdaupnCJCjSab6/JPvmdcQGQk5eSfVszrQzT0Ur8AFYwqSpz15BcXot+AlHepKK96bf6cgNeqboSjZD0/xVa6BoxHEk7OA0QKd2WkQS1jNO18dZxJCq1VicAwC5LkXOLWPINM8ilXqpRB1EvL9vN/V5b33wZ8Nmejs/0MxX7IEy38VTUwQMZ9yfJb8f8oKq
aws..s3.region=us-east-1

# ==========================================
# CONEXION A LA BASE DE DATOS DOCKERIZADA
# ==========================================
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/guias_semana5?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=guias_user
spring.datasource.password=guias1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.data.jpa.repositories.enabled=true